library(pastecs)
library(readr)
library(dplyr)
library(ggplot2)
roster_salary_stats<-read_csv("/Users/mAC/stat133/final/roster-salary-stats.csv")
#Disaggragate data by position
pg_stats<-filter(roster_salary_stats, position=='PG')
sg_stats<-filter(roster_salary_stats, position=='SG')
sf_stats<-filter(roster_salary_stats, position=='SF')
pf_stats<-filter(roster_salary_stats, position=='PF')
c_stats<-filter(roster_salary_stats, position=='C')
eda_output<-file(description = "/Users/mAC/stat133/final/data/cleandata/eda-output.txt")
options(tibble.print_max = Inf)
sink(file = eda_output, append = TRUE)
#Begin output
print("Frequencies for qualitative data")
by_pos<-summarise(group_by(roster_salary_stats, position), freq=n())
head(by_pos, n = 5)
by_team<-summarise(group_by(roster_salary_stats, Team), freq=n())
head(by_team, n = 30)
print("=====================================================================================")
print("Summary statistics for all players")
options(scipen=100)
options(digits=2)
attach(roster_salary_stats)
select_stats<-cbind(salary, height, weight, G, FG, FGA, FT, FTA, TRB, AST, STL, BLK, TOV, PF, PTS)
stat.desc(select_stats)
print("=====================================================================================")
print("Summary statistics by position")
print("Point guard")
attach(pg_stats)
select_stats<-cbind(salary, height, weight, G, FG, FGA, FT, FTA, TRB, AST, STL, BLK, TOV, PF, PTS)
stat.desc(select_stats)
print("-------------------------------------------------------------------------------------")
print("Shooting guard")
attach(sg_stats)
select_stats<-cbind(salary, height, weight, G, FG, FGA, FT, FTA, TRB, AST, STL, BLK, TOV, PF, PTS)
stat.desc(select_stats)
print("-------------------------------------------------------------------------------------")
print("Small forward")
attach(sf_stats)
select_stats<-cbind(salary, height, weight, G, FG, FGA, FT, FTA, TRB, AST, STL, BLK, TOV, PF, PTS)
stat.desc(select_stats)
print("-------------------------------------------------------------------------------------")
print("Power forward")
attach(pf_stats)
select_stats<-cbind(salary, height, weight, G, FG, FGA, FT, FTA, TRB, AST, STL, BLK, TOV, PF, PTS)
stat.desc(select_stats)
print("-------------------------------------------------------------------------------------")
print("Center")
attach(c_stats)
select_stats<-cbind(salary, height, weight, G, FG, FGA, FT, FTA, TRB, AST, STL, BLK, TOV, PF, PTS)
stat.desc(select_stats)
sink(file = NULL)
#Histograms and bar charts for each varaible
salary_gg<-ggplot(data = roster_salary_stats, aes(x = salary)) + ggtitle("Salary")
salary_gg + geom_histogram(binwidth = 1000000)
ggsave("/Users/mAC/stat133/final/images/salary_histogram.pdf")
height_gg<-ggplot(data = roster_salary_stats, aes(x = height)) + ggtitle("Height")
height_gg + geom_bar()
ggsave("/Users/mAC/stat133/final/images/height_bar.pdf")
weight_gg<-ggplot(data = roster_salary_stats, aes(x = weight)) + ggtitle("Weight")
weight_gg + geom_histogram(binwidth = 5)
ggsave("/Users/mAC/stat133/final/images/weight_histogram.pdf")
gp_hist<-ggplot(data = roster_salary_stats, aes(x = G))  + ggtitle("Games Played")
gp_hist + geom_histogram(binwidth = 5)
ggsave("/Users/mAC/stat133/final/images/games_played_histogram.pdf")
gp_hist + geom_bar()
ggsave("/Users/mAC/stat133/final/images/games_played_bar.pdf")
fg_hist<-ggplot(data = roster_salary_stats, aes(x = FG)) + ggtitle("Field Goals Made")
fg_hist + geom_histogram(binwidth = 10)
ggsave("/Users/mAC/stat133/final/images/field_goals_made_histograme.pdf")
fga_hist<-ggplot(data = roster_salary_stats, aes(x = FGA)) + ggtitle("Field Goals Attempted")
fga_hist + geom_histogram(binwidth = 10)
ggsave("/Users/mAC/stat133/final/images/field_goals_attempted_histogram.pdf")
ft_hist<-ggplot(data = roster_salary_stats, aes(x = FT)) + ggtitle("Free Throws Made")
ft_hist + geom_histogram(binwidth = 10)
ggsave("/Users/mAC/stat133/final/images/free_throws_made_histogram.pdf")
fta_hist<-ggplot(data = roster_salary_stats, aes(x = FTA)) + ggtitle("Free Throws Attempted")
fta_hist + geom_histogram(binwidth = 10)
ggsave("/Users/mAC/stat133/final/images/free_throw_attempt_histogram.pdf")
trb_hist<-ggplot(data = roster_salary_stats, aes(x = TRB)) + ggtitle("Total Rebounds")
trb_hist + geom_histogram(binwidth = 10)
ggsave("/Users/mAC/stat133/final/images/rebounds_histogram.pdf")
ast_hist<-ggplot(data = roster_salary_stats, aes(x = AST)) + ggtitle("Assists")
ast_hist + geom_histogram(binwidth = 10)
ggsave("/Users/mAC/stat133/final/images/assists_histogram.pdf")
stl_hist<-ggplot(data = roster_salary_stats, aes(x = STL)) + ggtitle("Steals")
stl_hist + geom_histogram(binwidth = 5)
ggsave("/Users/mAC/stat133/final/images/steal_histogram.pdf")
stl_hist + geom_bar()
ggsave("/Users/mAC/stat133/final/images/steal_bar.pdf")
blk_hist<-ggplot(data = roster_salary_stats, aes(x = BLK)) + ggtitle("Blocks")
blk_hist + geom_histogram(binwidth = 5)
ggsave("/Users/mAC/stat133/final/images/blocks_histogram.pdf")
blk_hist + geom_bar()
ggsave("/Users/mAC/stat133/final/images/blocks_bar.pdf")
tov_hist<-ggplot(data = roster_salary_stats, aes(x = TOV)) + ggtitle("Turnovers")
tov_hist + geom_histogram(binwidth = 5)
ggsave("/Users/mAC/stat133/final/images/turnover_histogram.pdf")
tov_hist + geom_bar()
ggsave("/Users/mAC/stat133/final/images/turnover_bar.pdf")
pf_hist<-ggplot(data = roster_salary_stats, aes(x = PF)) + ggtitle("Personal Fouls")
pf_hist + geom_histogram(binwidth = 5)
ggsave("/Users/mAC/stat133/final/images/fouls_histogram.pdf")
pf_hist + geom_bar()
ggsave("/Users/mAC/stat133/final/images/fouls_bar.pdf")
pts_hist<-ggplot(data = roster_salary_stats, aes(x = PTS)) + ggtitle("Points")
pts_hist + geom_histogram(binwidth = 25)
ggsave("/Users/mAC/stat133/final/images/points_histogram.pdf")
#Box plots
ggplot(data = roster_salary_stats, aes(x = Team, y = salary, group = Team)) + geom_boxplot() + ggtitle("Player Salary by Team")
ggsave("/Users/mAC/stat133/final/images/team_salary_boxplot.pdf")
ggplot(data = roster_salary_stats, aes(x = Team, y = PTS, group = Team)) + geom_boxplot() + ggtitle("Individual Points Scored by Team")
ggsave("/Users/mAC/stat133/final/images/team_points_boxplot.pdf")